services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start

  server:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    command: node server.js
